context:
  name: libusb
  version: 1.0.28

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://github.com/libusb/libusb/releases/download/v${{ version }}/${{ name }}-${{ version }}.tar.bz2
  sha256: 966bb0d231f94a474eaae2e67da5ec844d3527a1f386456394ff432580634b29

build:
  number: 1

requirements:
  run_exports:
    - ${{ pin_subpackage(name) }}
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    # cmake is only for doing string substitution for creating pkg-config file
    - if: win
      then:
        - cmake
    - if: unix
      then:
        - libtool
        - make
        - gnuconfig
        - automake 1.17.*

  host:
    - if: linux
      then: libudev

tests:
  - package_contents:
      include: 
        - libusb-1.0/libusb.h
      lib:
        - libusb-1.0

about:
  homepage: http://libusb.info/
  license: LGPL-2.1-or-later
  license_file: COPYING
  summary: A cross-platform library to access USB devices
  documentation: http://libusb.sourceforge.net/api-1.0/
  repository: https://github.com/libusb/libusb

extra:
  feedstock-name: libusb
  recipe-maintainers:
    - hoechenberger
    - kastman
    - ryanvolz
